[window]

opacity = 0.75
padding.x = 15
padding.y = 25
decorations = "None"

[font]

normal = { family = "MesloLGS NF", style = "Regular" }
size  = 19.0

[colors.primary]

foreground = "#FFFFFF"
background = "#0b0b0f"

[cursor]

style = { shape = "Beam", blinking = "Off"}

